version: "3.7"
services:
  app:
    image: thuicetea/sql-injection:v1
    container_name: sql-injection-app
    restart: always
    ports:
      - 80:80
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - sql-injection
  db:
    image: mysql:5.7
    container_name: sql-injection-db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - sql-injection

networks:
  sql-injection:
    driver: bridge